version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: faux
      POSTGRES_PASSWORD: genie
      POSTGRES_DB: dev
    ports:
      - "5434:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data

volumes:
  postgres_data: